# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
#
language: objective-c
osx_image: xcode12
xcode_project: Example/Mimir.xcodeproj # path to your xcodeproj folder
xcode_scheme: Mimir-Example
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro
cache: cocoapods
podfile: Example/Podfile
before_install:
    - gem install cocoapods # Since Travis is not always on latest version
    - pod install --project-directory=Example
script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Mimir.xcworkspace -scheme Mimir-Example -sdk iphonesimulator14.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --verbose
